"""add payment_proof_type and payment_proof to orders

Revision ID: 238f7be6911a
Revises: 0a19a4fad51a
Create Date: 2026-08-10 14:06:53.646913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238f7be6911a'
down_revision: Union[str, Sequence[str], None] = '0a19a4fad51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_proof_type', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('payment_proof', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_proof')
    op.drop_column('orders', 'payment_proof_type')
    # ### end Alembic commands ###
