"""add_is_active_to_products_and_temp

Revision ID: 2afe68beccaa
Revises: 1a2672db1b52
Create Date: 2026-08-07 18:40:40.628108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afe68beccaa'
down_revision: Union[str, Sequence[str], None] = '1a2672db1b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('temp_categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('temp_products', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_products', 'is_active')
    op.drop_column('temp_categories', 'is_active')
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
