"""initial schema

Revision ID: e2cd576ea91c
Revises: 
Create Date: 2026-09-09 11:34:47.521381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cd576ea91c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locale_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'language_code', name='uq_entity_lang')
    )
    with op.batch_alter_table('locale_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locale_texts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locale_texts_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_locale_texts_language_code'), ['language_code'], unique=False)

    op.create_table('temp_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_locale_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'language_code', 'admin_id', name='uq_temp_locale')
    )
    with op.batch_alter_table('temp_locale_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_locale_texts_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temp_locale_texts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temp_locale_texts_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_temp_locale_texts_language_code'), ['language_code'], unique=False)

    op.create_table('temp_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('delivery_address_type', sa.String(length=20), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_proof_type', sa.String(length=255), nullable=True),
    sa.Column('payment_proof', sa.Text(), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('templates')
    op.drop_table('temp_products')
    with op.batch_alter_table('temp_locale_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_locale_texts_language_code'))
        batch_op.drop_index(batch_op.f('ix_temp_locale_texts_entity_type'))
        batch_op.drop_index(batch_op.f('ix_temp_locale_texts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_temp_locale_texts_admin_id'))

    op.drop_table('temp_locale_texts')
    op.drop_table('temp_categories')
    with op.batch_alter_table('locale_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locale_texts_language_code'))
        batch_op.drop_index(batch_op.f('ix_locale_texts_entity_type'))
        batch_op.drop_index(batch_op.f('ix_locale_texts_entity_id'))

    op.drop_table('locale_texts')
    op.drop_table('categories')
    # ### end Alembic commands ###
